name: Main Workflow

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install
      - run: yarn build
      - run: yarn test
    
  sonarcloud:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish-npm:
    needs: sonarcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        if: startsWith(github.ref, 'refs/tags')
      - uses: actions/setup-node@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run:  yarn install && yarn build && yarn publish
        if: startsWith(github.ref, 'refs/tags')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}

  publish-gpr:
    needs: sonarcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        if: startsWith(github.ref, 'refs/tags')
      - uses: actions/setup-node@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com/
          scope: '@hmcts'
      - run: yarn install && yarn build && yarn publish
        if: startsWith(github.ref, 'refs/tags')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
